### ISSUE TITLE
Question: Possibility for batchprocessing? (XREADGROUP COUNT > 1)

### ISSUE THREAD

**Issue by 4ext** [gamaops/hfx-bus#15]
Hi,

thank you so much for your hard work!
There aren't a lot of projects utilizing redis streams at all and I love how very complete your implementation is!
I just read through the documentation and didn't find a way to fetch multiple items at once.
I know it's very event driven, but is this still possible somehow?

It would be awesome if up to X items could be read at once (non blocking) in intervals, for preprocessing them before processing and acknowledging them as a batch.

(Use case is some minor serialization during processing inside consumers running in parallel)

Thank you very much!

**Comment by vflopes** [comment]
@4ext , thank you!!! I love Redis and how streams are so powerful to deal with concurrency and messaging!

So, let me understand more of your use case: do you mean one job with multiple payloads to be processed or one consumer processing multiple jobs?

If you're talking about the second case, you can control the concurrency of your consumers through the **options.concurrency** parameter of [Consumer](https://github.com/gamaops/hfx-bus/blob/master/API.md#Consumer)

Let's say that you specify 10 as concurrency, so consumer will try to acquire at most 10 messages from the stream!

Is this enough or I'm misunderstanding your use case?

**Comment by 4ext** [comment]
@vflopes thank you very much for your kind reply!
I'm relatively new to Redis. 
It's very impressive and I'm starting to love it more and more ;)
The first time I decided to use it in my project was a few months back when I read through the excellent introduction about Redis Streams in 5.0. I used the Streams feature previously to append to a time series of data.


Then I needed a queue implementation for processing messages/jobs in intervals (let the queue grow as needed and process up to X amount of items per node per interval).

And thanks for your explanation! Unfortunately this isn't it. I did a poor job presenting the use case!

I looked at different implementations and noticed that most of them just called a number of consumers directly, which probably makes sense in most use cases and producer/consumer scenarios, but unfortunately not in my case.
Also almost none of them made use of the awesome Redis Streams feature addition in 5.0

I'm not sure if this is needed more often, but I'll tell you about my use case :)

I need to process in intervals (per consumer node/process). I could delay the messages, but this adds unneeded complexity, especially since this interval might change dynamically.

Even though the items (messages) are completely independent from each other, it might happen that some of them need to be processed a bit differently depending on what other items end up in the same batch together during an interval on the same node (and this also might change dynamically).

So the easiest solution is to grab a bunch of items (the next ones in the queue), up to the maximum amount the consumer is able to process concurrently, do some quick preprocessing, then process and finally xack the items.

All the other basic properties of a typical queue implementation are great (for other consumers to take over in case of problems, for an approximate ordering, horizontal scaling etc.), it's just the concurrency/event driven system that makes it impossible to use in my case.


Thanks for reading! I don't know if this makes any sense. For now I have started to implement this on my own, but of course I'd rather use a mature implementation.

I'm not asking you to make this possible with your library, like a feature request. It might be too exotic.
Just wanted to explain...

Thanks again and I wish you good luck and lots of fun with Redis in the future as well ;)

**Comment by vflopes** [comment]
@4ext , thank you very much and I hope you are having a very good experience with Redis!

Let me explain more about how HFXBus works, because I think is a little different interpretation of the queuing problem:

When you create a job (through `Producer.job()`) you're really just creating a reference (the job's ID) which implies two things:

1. That job can be put into one or more queues (including the same queue more than once)
2. That job can hold arbitrary data (using the job's `Job.set()` method)

Don't think the job is the a message *per se*, a job is a unit of work, a message is a signal that you send to consumers to do some work over that job.

So let's say that you have a consumer that receives a job and you want to put that job in another queue:

```typescript
consumer.process({
    stream: 'stream1',
    processor: async (job) => {

        // do some kind of pre-processing

        await producer.send({
            stream: 'stream2',
            waitFor: [
                'AnotherConsumerGroup'
            ],
            job
        });

        await job.finished();

    }
});
```

And if you want a "fire-and-forget" pattern, that is send the job and don't care about the completion:

```typescript
consumer.process({
    stream: 'stream1',
    processor: async (job) => {

        // do some kind of pre-processing

        await producer.send({
            stream: 'stream2',
            job
        });

    }
});
```

Now that we have this background knowledge, let's try to create a consumer that runs every 3 seconds and just process a single batch of items per round:

```typescript
consumer.process({
    stream: 'stream1',
    processor: async (job) => {

        consumer.emit('job.received');

        // do some kind of pre-processing

        await producer.send({
            stream: 'stream2',
            job
        });

    }
});

let isRunning = false;
const intervalId = setInterval(() => {
    if (isRunning)
        return;
    isRunning = true;
    consumer.play().catch((error) => {
        clearInterval(intervalId);
        // properly handle the error
    });
}, 3000);

consumer.on('job.received', () => {
    if (!isRunning)
        return;
    consumer.pause(() => {
        isRunning = false;
    }).catch((error) => {
        clearInterval(intervalId);
        consumer.removeAllListeners('job.received');
        // properly handle the error
    });
});
```

The message associated with a job is very lightweight, so you can have different pattern to achieve a "distribution" engine, I recommend that you create a pre-processing stream that consumers just do the pre-preprocessing job and use a producer to put them into specific streams, that can be delayed as I demonstrated in the example above. And more, if you want a "scheduling" mechanism you can just keep requeuing the job until the consumer decides it's time to process that job.

The processing interval can change dynamically and globally using Redis itself storing a key which points to global or specific consumers current interval (and you can use pub/sub to signal this change).

For traceability you can use the job's ID, it's immutable once the job was created.

I hope this explanation helped you to achieve your processing pattern requirements!
